export const products = [
  {
    title: "Walnuts",
    image1: "/walnuts/walnut1.jpg",
    image2: "/walnuts/walnut2.jpg",
    image3: "/walnuts/walnut3.jpg",
    price: 900,
    slug: "Walnuts",
    desc: "Meet our online store's special treat - walnuts! These little nuts are super healthy and tasty. They're full of good things like vitamins and that are good for your heart. You can eat them as a snack or add them to your food for some extra yumminess. Get your hands on these healthy munchies at our online dry fruit store.",
  },
  {
    title: "Salajeet",
    image1: "/salajeet/salajeet1.png",
    image2: "/salajeet/salajeet2.jpg",
    // image3: "/walnuts/walnut3.jpg",
    price: 600,
    slug: "Salajeet",
    desc: "In the heart of the majestic Himalayan mountains lies a hidden treasure known as organic Salajeet, a unique substance revered for its remarkable health benefits. Salajeet, also spelled Shilajit, is a resinous substance that oozes from the cracks of rocks in these pristine mountains. For centuries, it has been a cornerstone of traditional Ayurvedic medicine, cherished for its ability to promote overall well-being.",
  },
  {
    title: "Almonds",
    image1: "/almond/almond1.jpg",
    image2: "/almond/almond2.jpg",
    image3: "/almond/almond3.jpg",
    price: 1200,
    slug: "Almonds",
    desc: `Available Gilgit Baltistan Good quality Almonds at Reliable Price.  Almonds, the humble nuts that they are, hold a special place in the world of nutrition. These small, unassuming morsels pack a powerful punch when it comes to health benefits. In this extensive exploration of almonds, we will delve into their history, nutrition, culinary uses, and their remarkable impact on overall well-being.`,
  },
  {
    title: "Dry Cherry",
    image1: "/cherry/cherry1.jpg",
    image2: "/cherry/cherry2.jpg",
    image3: "/cherry/cherry3.jpeg",
    price: 1000,
    slug: "Dry-Cherry",
    desc: `Available Gilgit Baltistan Dry Fruit at Reliable Price.
     Dry cherries, sometimes called dried cherries or tart cherries, are like little bursts of sweetness and goodness. These tiny red fruits are made by drying fresh cherries, which makes them sweeter and super tasty.`,
  },
  {
    title: "Apricot",
    image1: "/apricot/apricot1.jpeg",
    image2: "/apricot/apricot2.jpeg",
    image3: "/apricot/apricot3.jpeg",
    price: 800,
    slug: "Apricot",
    desc: `Available Gilgit Baltistan Dry Fruit at Reliable Price. Apricots are a yummy fruit that's really good for you. They're orange, and they've been loved by people for a very long time. Here's why: Lots of Good Stuff: Apricots are full of vitamins and fiber. They have vitamin A, which is great for your eyes, and vitamin C, which helps your body fight sickness.`,
  },
  {
    title: "Kilawo",
    image1: "/khilao/khilao1.jpeg",
    image2: "/khilao/khilao2.jpeg",
    image3: "/khilao/khilao3.jpeg",
    price: 2500,
    slug: "kilawo",
    desc: `Available Gilgit Baltistan Dry Fruit at Reliable Price.A perfect combination of walnut and melburry (Gilgiti Chocolate) Kilawo. Kilawo is a special product from Gilgit Baltistan that is only available in the region. It is a walnut coated with grapes juice, which contains grapes, apricot, and mulberries`,
  },
];
